### ISSUE TITLE
关于网络结构和dataset类的疑惑

### ISSUE THREAD

**Issue by Willianwatch** [taozh2017/HiNet#17]
#### 网络结构
在syn_model的__init__函数中所定义的out1和out2在forward方法里面没有使用，主要是下面两个地方：
- [out1](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/model/syn_model.py#L258)
- [out2](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/model/syn_model.py#L267)
#### dataset类
从[loadSubjectData](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/dataset.py#L18)可以看出数据是三维的，但是随后在[generate_all_patches函数](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/funcs/utils.py#L61)里面数据又是二维的

能否解释下这两个地方，先谢谢大佬了

**Comment by taozh2017** [comment]
> 

（1）后面使用了output1和output2；
（2）这里是先读取三维的一个subject，然后每个subject数据产生多个二维的小patch。其中，网络的输入是二维图像。

**Comment by Willianwatch** [comment]
我的意思是，您在[这里](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/model/syn_model.py#L184)定义了self.out1，但是在forward方法里面的得到out1的[这一步](https://github.com/taozh2017/HiNet/blob/c4c00d2851be3a6bd505fbb7f697eae5ff84c5ef/model/syn_model.py#L258)却没有使用前面定义的self.out1来卷积。out2也是这样。按照您论文里面的网络结构，这个三个分支应该是没有使用同一个输出卷积的，略有点疑惑。

**Comment by taozh2017** [comment]
> 

这里我忘记update了，应该是三个分别用三个不同的卷积。

**Comment by Willianwatch** [comment]
好的，那就没啥问题了，谢谢！
