### ISSUE TITLE
wrong import of ssim

### ISSUE THREAD

**Issue by JianJuly** [taozh2017/HiNet#2]
https://github.com/taozh2017/HiNet/blob/ae2dc3e118921f0ce1436a0123720d6305b320ee/funcs/utils.py#L15

**Comment by taozh2017** [comment]
Can you try to first install it?
--> pip install scikit-image

**Comment by JianJuly** [comment]
I meant that line 15 and line 16  are duplicated
```
from skimage.measure import structural_similarity as ssim
from skimage.measure import compare_ssim as ssim
```
