### ISSUE TITLE
An error in function call

### ISSUE THREAD

**Issue by Zehui-Lin** [taozh2017/HiNet#5]
🐛 BUG
---
According to https://github.com/taozh2017/HiNet/blob/fd67f648464581eb77af43bfc5a8623944c301a7/model/syn_model.py#L42,
the function call here in
https://github.com/taozh2017/HiNet/blob/fd67f648464581eb77af43bfc5a8623944c301a7/model/syn_model.py#L234 and https://github.com/taozh2017/HiNet/blob/fd67f648464581eb77af43bfc5a8623944c301a7/model/syn_model.py#L237 should be
```python
down_fu_2 = self.down_fu_2(down_2_0m, down_2_1m, down_fu_1m)
down_fu_3 = self.down_fu_3(down_3_0m, down_3_1m, down_fu_2m)
```
instead.

**Comment by taozh2017** [comment]
Thanks. I have corrected it.
