### ISSUE TITLE
How to convert a file in nii format to mat format？

### ISSUE THREAD

**Issue by liyiersan** [taozh2017/HiNet#6]
I downloaded the  BraTs2018 dataset from the website, but it seems that the format in this dataset is nii while the files in data directory are in mat format. Could you please show me how to a file in nii format to mat format with python?

**Comment by taozh2017** [comment]
I used load_nii.m (matlab function) to load and then save to "mat" format. Pls refer it: https://stackoverflow.com/questions/29088642/how-to-transfer-nifti-file-into-mat-matlab-file.
Thanks.

**Comment by liyiersan** [comment]
So sorry to disturb you again, I am poor in programming, so could you please show me your matlab files to me? I would be very grateful if you could help me.

**Comment by taozh2017** [comment]
Give me your email.

**Comment by liyiersan** [comment]
ZhouQianHS@163.com, thank you very much!!!!!

**Comment by liyiersan** [comment]
Thank you very much. Under your guidance, I finally know how to convert the format. I need to put the img data in a struct instead of saving the original data directly. Wishing a happy, long and healthy life!!!

**Comment by taozh2017** [comment]
It's great. Thx.

**Comment by huaibovip** [comment]
Hi, 
could you share data preprocessing code with me?

**Comment by taozh2017** [comment]
Please find it at ./tool/NIFTI_tool.rar
